
spring:
  datasource:
    dynamic:
      # ??????????????,?????master
      primary: master
      # ???????,??false. true?????????????,false???????
      strict: false
      datasource:
        master:
          # 3.2.0????SPI??????
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://rm-cn-x0r3h12hm000hyzo.rwlb.rds.aliyuncs.com:3306/tmp_scctp?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
          username: u_jjsunw
          password: u_jjsunw@123
          type: com.alibaba.druid.pool.DruidDataSource
        slave:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://rm-cn-x0r3h12hm000hyzo.rwlb.rds.aliyuncs.com:3306/u_nacos_config?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
          username: u_jjsunw
          password: u_jjsunw@123
          type: com.alibaba.druid.pool.DruidDataSource
      # ???? druid ???
      druid:
        # ????????
        initial-size: 5
        # ???????
        min-idle: 10
        # ?????
        max-active: 20
        # ?????????????
        maxWait: 60000
        # ?????????????,???????????,?????
        timeBetweenEvictionRunsMillis: 60000
        # ????????????????,?????
        minEvictableIdleTimeMillis: 300000
        # ????????????????,?????
        maxEvictableIdleTimeMillis: 900000
        # ??????????
        validationQuery: SELECT 1 FROM DUAL


        #......??
        #??????????master,???slave??????slave_1,slave_2

mybatis:
  mapper-locations: classpath:org/relaxation/dynamicdatasource/dao/**/*.xml
  type-aliases-package: org.relaxation.dynamicdatasource.entity
