spring:
  influx:
    url: http://10.24.66.60:8086
    user: admin
    password: qwer1234
    database: toolkit
management:
  server:
    port: 9999
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env,beans
      base-path: /monitor